"""Productsales table column removed

Revision ID: 3df432d18786
Revises: 3315c1bc4230
Create Date: 2024-10-23 12:41:48.504066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3df432d18786'
down_revision = '3315c1bc4230'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_sales', schema=None) as batch_op:
        batch_op.drop_column('sale_profit_margin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sale_profit_margin', sa.NUMERIC(precision=10, scale=2), nullable=False))

    # ### end Alembic commands ###
