"""quantity_purchased column updated

Revision ID: c1d183b1e556
Revises: e4813b7cf0aa
Create Date: 2024-12-17 18:28:12.433905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1d183b1e556'
down_revision = 'e4813b7cf0aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('costs', schema=None) as batch_op:
        batch_op.alter_column('quantity_purchased',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('costs', schema=None) as batch_op:
        batch_op.alter_column('quantity_purchased',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###
